// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/food/data/models/food_log_entity.dart';
import 'features/pet/data/models/pet_entity.dart';
import 'features/user/data/models/user_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8969489880642630653),
    name: 'UserEntity',
    lastPropertyId: const obx_int.IdUid(5, 468359755930285326),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3756887049867524224),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1095928158348022768),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6861776087152607584),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1103686336142285649),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 468359755930285326),
        name: 'photoPath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7190639932575767621),
    name: 'FoodLogEntity',
    lastPropertyId: const obx_int.IdUid(8, 6543491016059924),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8168052279142380922),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6785722462571130404),
        name: 'foodName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 704541705861918533),
        name: 'calories',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3438631998267807140),
        name: 'protein',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5713020604719377356),
        name: 'carbs',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6430850188894604022),
        name: 'fat',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1410380697912162436),
        name: 'imagePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6543491016059924),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 783428171470640664),
    name: 'PetEntity',
    lastPropertyId: const obx_int.IdUid(8, 5713754980626256512),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8038105039076692754),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4292303367666524408),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3154268870460813651),
        name: 'species',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7954506711847462263),
        name: 'imagePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 629167436274531319),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6047037066559026534),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 322402669160939439),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 8879275025653982067),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5713754980626256512),
        name: 'breed',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 783428171470640664),
    lastIndexId: const obx_int.IdUid(1, 8879275025653982067),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    UserEntity: obx_int.EntityDefinition<UserEntity>(
      model: _entities[0],
      toOneRelations: (UserEntity object) => [],
      toManyRelations: (UserEntity object) => {},
      getId: (UserEntity object) => object.id,
      setId: (UserEntity object, int id) {
        object.id = id;
      },
      objectToFB: (UserEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final emailOffset = fbb.writeString(object.email);
        final photoPathOffset = object.photoPath == null
            ? null
            : fbb.writeString(object.photoPath!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, emailOffset);
        fbb.addBool(3, object.isActive);
        fbb.addOffset(4, photoPathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final isActiveParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final photoPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final object = UserEntity(
          id: idParam,
          name: nameParam,
          email: emailParam,
          isActive: isActiveParam,
          photoPath: photoPathParam,
        );

        return object;
      },
    ),
    FoodLogEntity: obx_int.EntityDefinition<FoodLogEntity>(
      model: _entities[1],
      toOneRelations: (FoodLogEntity object) => [],
      toManyRelations: (FoodLogEntity object) => {},
      getId: (FoodLogEntity object) => object.id,
      setId: (FoodLogEntity object, int id) {
        object.id = id;
      },
      objectToFB: (FoodLogEntity object, fb.Builder fbb) {
        final foodNameOffset = fbb.writeString(object.foodName);
        final imagePathOffset = fbb.writeString(object.imagePath);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, foodNameOffset);
        fbb.addFloat64(2, object.calories);
        fbb.addFloat64(3, object.protein);
        fbb.addFloat64(4, object.carbs);
        fbb.addFloat64(5, object.fat);
        fbb.addOffset(6, imagePathOffset);
        fbb.addInt64(7, object.timestamp.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final foodNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final caloriesParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final proteinParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final carbsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final fatParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final imagePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final object = FoodLogEntity(
          id: idParam,
          foodName: foodNameParam,
          calories: caloriesParam,
          protein: proteinParam,
          carbs: carbsParam,
          fat: fatParam,
          imagePath: imagePathParam,
          timestamp: timestampParam,
        );

        return object;
      },
    ),
    PetEntity: obx_int.EntityDefinition<PetEntity>(
      model: _entities[2],
      toOneRelations: (PetEntity object) => [],
      toManyRelations: (PetEntity object) => {},
      getId: (PetEntity object) => object.id,
      setId: (PetEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PetEntity object, fb.Builder fbb) {
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final speciesOffset = fbb.writeString(object.species);
        final imagePathOffset = fbb.writeString(object.imagePath);
        final typeOffset = object.type == null
            ? null
            : fbb.writeString(object.type!);
        final uuidOffset = fbb.writeString(object.uuid);
        final breedOffset = object.breed == null
            ? null
            : fbb.writeString(object.breed!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, speciesOffset);
        fbb.addOffset(3, imagePathOffset);
        fbb.addOffset(4, typeOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(6, uuidOffset);
        fbb.addOffset(7, breedOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final breedParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final speciesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final imagePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final object = PetEntity(
          id: idParam,
          uuid: uuidParam,
          name: nameParam,
          breed: breedParam,
          species: speciesParam,
          imagePath: imagePathParam,
          type: typeParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [UserEntity] entity fields to define ObjectBox queries.
class UserEntity_ {
  /// See [UserEntity.id].
  static final id = obx.QueryIntegerProperty<UserEntity>(
    _entities[0].properties[0],
  );

  /// See [UserEntity.name].
  static final name = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[1],
  );

  /// See [UserEntity.email].
  static final email = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[2],
  );

  /// See [UserEntity.isActive].
  static final isActive = obx.QueryBooleanProperty<UserEntity>(
    _entities[0].properties[3],
  );

  /// See [UserEntity.photoPath].
  static final photoPath = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[4],
  );
}

/// [FoodLogEntity] entity fields to define ObjectBox queries.
class FoodLogEntity_ {
  /// See [FoodLogEntity.id].
  static final id = obx.QueryIntegerProperty<FoodLogEntity>(
    _entities[1].properties[0],
  );

  /// See [FoodLogEntity.foodName].
  static final foodName = obx.QueryStringProperty<FoodLogEntity>(
    _entities[1].properties[1],
  );

  /// See [FoodLogEntity.calories].
  static final calories = obx.QueryDoubleProperty<FoodLogEntity>(
    _entities[1].properties[2],
  );

  /// See [FoodLogEntity.protein].
  static final protein = obx.QueryDoubleProperty<FoodLogEntity>(
    _entities[1].properties[3],
  );

  /// See [FoodLogEntity.carbs].
  static final carbs = obx.QueryDoubleProperty<FoodLogEntity>(
    _entities[1].properties[4],
  );

  /// See [FoodLogEntity.fat].
  static final fat = obx.QueryDoubleProperty<FoodLogEntity>(
    _entities[1].properties[5],
  );

  /// See [FoodLogEntity.imagePath].
  static final imagePath = obx.QueryStringProperty<FoodLogEntity>(
    _entities[1].properties[6],
  );

  /// See [FoodLogEntity.timestamp].
  static final timestamp = obx.QueryDateProperty<FoodLogEntity>(
    _entities[1].properties[7],
  );
}

/// [PetEntity] entity fields to define ObjectBox queries.
class PetEntity_ {
  /// See [PetEntity.id].
  static final id = obx.QueryIntegerProperty<PetEntity>(
    _entities[2].properties[0],
  );

  /// See [PetEntity.name].
  static final name = obx.QueryStringProperty<PetEntity>(
    _entities[2].properties[1],
  );

  /// See [PetEntity.species].
  static final species = obx.QueryStringProperty<PetEntity>(
    _entities[2].properties[2],
  );

  /// See [PetEntity.imagePath].
  static final imagePath = obx.QueryStringProperty<PetEntity>(
    _entities[2].properties[3],
  );

  /// See [PetEntity.type].
  static final type = obx.QueryStringProperty<PetEntity>(
    _entities[2].properties[4],
  );

  /// See [PetEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<PetEntity>(
    _entities[2].properties[5],
  );

  /// See [PetEntity.uuid].
  static final uuid = obx.QueryStringProperty<PetEntity>(
    _entities[2].properties[6],
  );

  /// See [PetEntity.breed].
  static final breed = obx.QueryStringProperty<PetEntity>(
    _entities[2].properties[7],
  );
}
